### ISSUE TITLE
Allow either `goaws.yml` or `goaws.yaml` config by default

### ISSUE THREAD

**Issue by danilofuchs** [Admiral-Piett/goaws#239]
I've had much trouble trying to configure the project by making the mistake of naming the file as `goaws.yml`

The extension is interchangeable in many contexts, but goaws expects `.yaml`

**Comment by danilofuchs** [comment]
That was a long time ago, I probably didn't realize there was a config flag.

It should probably be closed, does not make much sense to maintain 2 default file names and .yaml is much more common

**Comment by Admiral-Piett** [comment]
Awesome, that's exactly what I was thinking too.  Thanks @danilofuchs for clarifying.  Closing this out.
