### ISSUE TITLE
What is the project state ?

### ISSUE THREAD

**Issue by williamdes** [Admiral-Piett/goaws#246]
Hi @p4tin 
My client uses your container since years now, what is the state of this project ?

Can you release the latest changes ?

**Comment by fffinkel** [comment]
We're wondering this as well. We're happy to take over maintainership if the current maintainer no longer has the time.

**Comment by pfortin-urbn** [comment]
I am looking into passing the torch - thank you all for using goaws!!

**Comment by williamdes** [comment]
> I am looking into passing the torch - thank you all for using goaws!!

You can transfer it to @code-lts where you will/can keep rights and other people can contribute to it

**Comment by Admiral-Piett** [comment]
We've transitioned the ownership to me now.  So I'm ramping up on outstanding issues, and the general state of the union.  Let me know if you have any outstanding issues or questions.  Thanks!

**Comment by williamdes** [comment]
> We've transitioned the ownership to me now. So I'm ramping up on outstanding issues, and the general state of the union. Let me know if you have any outstanding issues or questions. Thanks!

Do you also have access to the Docker image?
or get it deleted and create a new one

**Comment by fffinkel** [comment]
@Admiral-Piett thank you so much for taking this over, and @pfortin-urbn thank you for your response and passing the torch!

**Comment by Admiral-Piett** [comment]
@williamdes yep, for now the new images are located below.  Anything pre-v0.3.2 is still at `pafortin/goaws`.  I'm looking into copying the old versions onto this registry, but one of many things on my todo list atm.

- `docker pull admiralpiett/goaws`
- `docker pull admiralpiett/goaws:v0.4.1`.  # republished just now
- `docker pull admiralpiett/goaws:latest`

**Comment by williamdes** [comment]
I honestly think it's best to continue uploading to the original image or to take down all images of the original image and host yours as said above.

I am interested in contributing a multi arch build when you tell me that the builds are golang up to date and working
