### ISSUE TITLE
Old release v1.1.2 is marked as latest

### ISSUE THREAD

**Issue by jesusfcr** [Admiral-Piett/goaws#265]
Hi @Admiral-Piett 

First, thanks for taking the time of maintaining this project.

Looking into the releases/tags of the project I see they are not congruent with the dates.

```sh
go list -versions -m github.com/Admiral-Piett/goaws
github.com/Admiral-Piett/goaws v0.2.0 v0.2.1 v0.2.2 v0.3.0 v0.3.1 v0.3.2 v0.4.0 v0.4.1 v1.1.0 v1.1.1 v1.1.2

go get github.com/Admiral-Piett/goaws@latest
go: added github.com/Admiral-Piett/goaws v1.1.2
```

It seems clear the last one is the `v0.4.1`, so the `v1` releases are interfering.

This could be solved by [retracting](https://golangtutorial.dev/tips/retract-go-module-versions/#retracting-multiple-go-module-versions) the v1 versions just adding that on your `go.mod`.

```
retract (
        v1.1.0
        v1.1.1
        v1.1.2
)
```

**Comment by goddenrich** [comment]
Hi @Admiral-Piett I am still seeing the old version as latest and it appears the retractions are not doing what they are intending to do 
```
$ go list -versions -m github.com/Admiral-Piett/goaws
github.com/Admiral-Piett/goaws v0.2.0 v0.2.1 v0.2.2 v0.3.0 v0.3.1 v0.3.2 v0.4.0 v0.4.1 v0.4.2 v0.4.3 v0.4.4 v0.4.5 v1.1.0 v1.1.1 v1.1.2
$ go list -versions -m -retracted github.com/Admiral-Piett/goaws
github.com/Admiral-Piett/goaws v0.2.0 v0.2.1 v0.2.2 v0.3.0 v0.3.1 v0.3.2 v0.4.0 v0.4.1 v0.4.2 v0.4.3 v0.4.4 v0.4.5 v1.1.0 v1.1.1 v1.1.2
```

**Comment by jesusfcr** [comment]
Hi, I think this explains the reason why and how to solve it https://www.jvt.me/posts/2024/01/15/retract-go-release/

**Comment by goddenrich** [comment]
@jesusfcr if i'm understanding correctly this library needs to tag a new release as v1.1.3 which contains 
```
retract(
     v1.1.0
     v1.1.1
     v1.1.2
     v1.1.3
)
```
is that correct? If so @Admiral-Piett could you do that?

**Comment by Admiral-Piett** [comment]
@jesusfcr @goddenrich - let me know if you're still having trouble with this.  It's been a real mess - I added a couple minor things and threw a new version out there.  It's working for me, but locally I did have to do a `go get github.com/Admiral-Piett/goaws@v0.4.7` to get the go module proxy to bypass the `1.1.x` versions.  I think that should do it though - it's now seeing `v0.4.7` as latest for me anyway.  Small progress?

**Comment by goddenrich** [comment]
v1.1.3 still seems to be latest for me but now v1.1.1 and v1.1.2 seem to properly be retracted
```
$ go list -versions -m github.com/Admiral-Piett/goaws
github.com/Admiral-Piett/goaws v0.2.0 v0.2.1 v0.2.2 v0.3.0 v0.3.1 v0.3.2 v0.4.0 v0.4.1 v0.4.2 v0.4.3 v0.4.4 v0.4.5 v0.4.6 v0.4.7 v0.4.8 v1.1.3
$ go get github.com/Admiral-Piett/goaws@v0.4.7
go: downloading github.com/Admiral-Piett/goaws v0.4.5
go: upgraded github.com/Admiral-Piett/goaws v0.4.6 => v0.4.7
$ go list -versions -m github.com/Admiral-Piett/goaws
github.com/Admiral-Piett/goaws v0.2.0 v0.2.1 v0.2.2 v0.3.0 v0.3.1 v0.3.2 v0.4.0 v0.4.1 v0.4.2 v0.4.3 v0.4.4 v0.4.5 v0.4.6 v0.4.7 v0.4.8 v1.1.3
$ go get -u github.com/Admiral-Piett/goaws
go: upgraded github.com/Admiral-Piett/goaws v0.4.7 => v1.1.3
```

**Comment by Admiral-Piett** [comment]
@goddenrich Try to pull v0.4.7 or v0.4.8 manually (the full command is in my note above).  I bet your go module proxy needs to update and get forced onto the new track.  Since there is no v1.1.3 anymore.

**Comment by goddenrich** [comment]
ah removing the `$GOPATH/pkg/sum.golang.org/latest` and rerunning 
```
rgodden@rgodden-tm05522:~/repos/core3/src$ go list -versions -m github.com/Admiral-Piett/goaws
github.com/Admiral-Piett/goaws v0.2.0 v0.2.1 v0.2.2 v0.3.0 v0.3.1 v0.3.2 v0.4.0 v0.4.1 v0.4.2 v0.4.3 v0.4.4 v0.4.5 v0.4.6 v0.4.7 v0.4.8
```

**Comment by jesusfcr** [comment]
@Admiral-Piett for me it's as expected.
Thanks a lot for takin care of it!
