### ISSUE TITLE
SQS AWS JSON-1.0 gives bad request

### ISSUE THREAD

**Issue by renatolond** [Admiral-Piett/goaws#279]
Hi! Thanks for your work in goaws!

I tried upgrading one of our projects to the latest `aws-sdk-sqs` ruby gem version and I started getting bad requests from goaws. It seems that they introduced a new protocol called AWS JSON-1.0. Is this something that will get integrated into goaws?
https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-sqs/CHANGELOG.md#1660-2023-11-08

**Comment by Admiral-Piett** [comment]
@renatolond If you're still having issues, v0.5.0 supports AWS JSON 1.1 Protocol - try that.  If that fails feel free to comment back here.
