### ISSUE TITLE
Boto3 SNS Publish

### ISSUE THREAD

**Issue by advancedlogic** [Admiral-Piett/goaws#298]
When I try to publish a message using boto3:

```
self.sns.publish(
                TopicArn=topic,
                Message= json.dumps({
                    'default': message
                }),
                MessageStructure='json'
            )
```

I get this error on the docker log:

2024/04/12 22:04:22 http: panic serving 192.168.65.1:64968: invalid WriteHeader code 0
sqs       | goroutine 313 [running]:
sqs       | net/http.(*conn).serve.func1()
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1825 +0xbf
sqs       | panic({0x6fc9c0, 0xc0000111e0})
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:844 +0x258
sqs       | net/http.checkWriteHeaderCode(...)
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1111
sqs       | net/http.(*response).WriteHeader(0xc0004f8460, 0x0)
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1145 +0x879
sqs       | github.com/Admiral-Piett/goaws/app/gosns.createErrorResponse({0x7ef3b8, 0xc0004f8460}, 0x4a?, {0xc0000ac300?, 0x0?})
sqs       |     /home/runner/work/goaws/goaws/app/gosns/gosns.go:777 +0x134
sqs       | github.com/Admiral-Piett/goaws/app/gosns.publishSQS({0x7ef3b8, 0xc0004f8460}, 0xc0002a03f0?, 0xc0001500a0, {0xc000014230, 0x4a}, 0xc000723470, {0x0, 0x0}, {0xc0000141e0, ...}, ...)
sqs       |     /home/runner/work/goaws/goaws/app/gosns/gosns.go:548 +0x551
sqs       | github.com/Admiral-Piett/goaws/app/gosns.Publish({0x7ef3b8, 0xc0004f8460}, 0xc00027a007?)
sqs       |     /home/runner/work/goaws/goaws/app/gosns/gosns.go:510 +0x4ea
sqs       | net/http.HandlerFunc.ServeHTTP(...)
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2084
sqs       | github.com/Admiral-Piett/goaws/app/router.actionHandler({0x7ef3b8, 0xc0004f8460}, 0xc000229100)
sqs       |     /home/runner/work/goaws/goaws/app/router/router.go:79 +0x1f4
sqs       | net/http.HandlerFunc.ServeHTTP(0xc000229000?, {0x7ef3b8?, 0xc0004f8460?}, 0x0?)
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2084 +0x2f
sqs       | github.com/gorilla/mux.(*Router).ServeHTTP(0xc000254300, {0x7ef3b8, 0xc0004f8460}, 0xc000228f00)
sqs       |     /home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
sqs       | net/http.serverHandler.ServeHTTP({0x7ee6f0?}, {0x7ef3b8, 0xc0004f8460}, 0xc000228f00)
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2916 +0x43b
sqs       | net/http.(*conn).serve(0xc0002b21e0, {0x7ef670, 0xc00029c450})
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1966 +0x5d7
sqs       | created by net/http.(*Server).Serve
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:3071 +0x4db
sqs       | 2024/04/12 22:04:22 http: panic serving 192.168.65.1:64971: invalid WriteHeader code 0
sqs       | goroutine 323 [running]:
sqs       | net/http.(*conn).serve.func1()
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1825 +0xbf
sqs       | panic({0x6fc9c0, 0xc000011340})
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:844 +0x258
sqs       | net/http.checkWriteHeaderCode(...)
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1111
sqs       | net/http.(*response).WriteHeader(0xc0004f8540, 0x0)
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1145 +0x879
sqs       | github.com/Admiral-Piett/goaws/app/gosns.createErrorResponse({0x7ef3b8, 0xc0004f8540}, 0x4a?, {0xc0000ac480?, 0x0?})
sqs       |     /home/runner/work/goaws/goaws/app/gosns/gosns.go:777 +0x134
sqs       | github.com/Admiral-Piett/goaws/app/gosns.publishSQS({0x7ef3b8, 0xc0004f8540}, 0xc0002a04d0?, 0xc0001500a0, {0xc000014320, 0x4a}, 0xc0007238c0, {0x0, 0x0}, {0xc0000142d0, ...}, ...)
sqs       |     /home/runner/work/goaws/goaws/app/gosns/gosns.go:548 +0x551
sqs       | github.com/Admiral-Piett/goaws/app/gosns.Publish({0x7ef3b8, 0xc0004f8540}, 0xc00027a127?)
sqs       |     /home/runner/work/goaws/goaws/app/gosns/gosns.go:510 +0x4ea
sqs       | net/http.HandlerFunc.ServeHTTP(...)
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2084
sqs       | github.com/Admiral-Piett/goaws/app/router.actionHandler({0x7ef3b8, 0xc0004f8540}, 0xc000229400)
sqs       |     /home/runner/work/goaws/goaws/app/router/router.go:79 +0x1f4
sqs       | net/http.HandlerFunc.ServeHTTP(0xc000229300?, {0x7ef3b8?, 0xc0004f8540?}, 0x0?)
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2084 +0x2f
sqs       | github.com/gorilla/mux.(*Router).ServeHTTP(0xc000254300, {0x7ef3b8, 0xc0004f8540}, 0xc000229200)
sqs       |     /home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
sqs       | net/http.serverHandler.ServeHTTP({0x7ee6f0?}, {0x7ef3b8, 0xc0004f8540}, 0xc000229200)
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2916 +0x43b
sqs       | net/http.(*conn).serve(0xc00013ba40, {0x7ef670, 0xc00029c450})
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1966 +0x5d7
sqs       | created by net/http.(*Server).Serve
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:3071 +0x4db
sqs       | 2024/04/12 22:04:24 http: panic serving 192.168.65.1:64972: invalid WriteHeader code 0
sqs       | goroutine 304 [running]:
sqs       | net/http.(*conn).serve.func1()
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1825 +0xbf
sqs       | panic({0x6fc9c0, 0xc00024eef0})
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:844 +0x258
sqs       | net/http.checkWriteHeaderCode(...)
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1111
sqs       | net/http.(*response).WriteHeader(0xc00028a7e0, 0x0)
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1145 +0x879
sqs       | github.com/Admiral-Piett/goaws/app/gosns.createErrorResponse({0x7ef3b8, 0xc00028a7e0}, 0x4a?, {0xc00072e480?, 0x0?})
sqs       |     /home/runner/work/goaws/goaws/app/gosns/gosns.go:777 +0x134
sqs       | github.com/Admiral-Piett/goaws/app/gosns.publishSQS({0x7ef3b8, 0xc00028a7e0}, 0xc000274540?, 0xc0001500a0, {0xc000144500, 0x4a}, 0xc0001210b0, {0x0, 0x0}, {0xc0001444b0, ...}, ...)
sqs       |     /home/runner/work/goaws/goaws/app/gosns/gosns.go:548 +0x551
sqs       | github.com/Admiral-Piett/goaws/app/gosns.Publish({0x7ef3b8, 0xc00028a7e0}, 0xc0002d2007?)
sqs       |     /home/runner/work/goaws/goaws/app/gosns/gosns.go:510 +0x4ea
sqs       | net/http.HandlerFunc.ServeHTTP(...)
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2084
sqs       | github.com/Admiral-Piett/goaws/app/router.actionHandler({0x7ef3b8, 0xc00028a7e0}, 0xc000289600)
sqs       |     /home/runner/work/goaws/goaws/app/router/router.go:79 +0x1f4
sqs       | net/http.HandlerFunc.ServeHTTP(0xc000289500?, {0x7ef3b8?, 0xc00028a7e0?}, 0x0?)
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2084 +0x2f
sqs       | github.com/gorilla/mux.(*Router).ServeHTTP(0xc000254300, {0x7ef3b8, 0xc00028a7e0}, 0xc000289400)
sqs       |     /home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
sqs       | net/http.serverHandler.ServeHTTP({0x7ee6f0?}, {0x7ef3b8, 0xc00028a7e0}, 0xc000289400)
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2916 +0x43b
sqs       | net/http.(*conn).serve(0xc0000a85a0, {0x7ef670, 0xc00029c450})
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1966 +0x5d7
sqs       | created by net/http.(*Server).Serve
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:3071 +0x4db
sqs       | 2024/04/12 22:04:24 http: panic serving 192.168.65.1:64973: invalid WriteHeader code 0
sqs       | goroutine 325 [running]:
sqs       | net/http.(*conn).serve.func1()
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1825 +0xbf
sqs       | panic({0x6fc9c0, 0xc000011560})
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:844 +0x258
sqs       | net/http.checkWriteHeaderCode(...)
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1111
sqs       | net/http.(*response).WriteHeader(0xc0004f8620, 0x0)
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1145 +0x879
sqs       | github.com/Admiral-Piett/goaws/app/gosns.createErrorResponse({0x7ef3b8, 0xc0004f8620}, 0x4a?, {0xc0000ac580?, 0x0?})
sqs       |     /home/runner/work/goaws/goaws/app/gosns/gosns.go:777 +0x134
sqs       | github.com/Admiral-Piett/goaws/app/gosns.publishSQS({0x7ef3b8, 0xc0004f8620}, 0xc0002a05b0?, 0xc0001500a0, {0xc000014410, 0x4a}, 0xc000723d10, {0x0, 0x0}, {0xc0000143c0, ...}, ...)
sqs       |     /home/runner/work/goaws/goaws/app/gosns/gosns.go:548 +0x551
sqs       | github.com/Admiral-Piett/goaws/app/gosns.Publish({0x7ef3b8, 0xc0004f8620}, 0xc00027a247?)
sqs       |     /home/runner/work/goaws/goaws/app/gosns/gosns.go:510 +0x4ea
sqs       | net/http.HandlerFunc.ServeHTTP(...)
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2084
sqs       | github.com/Admiral-Piett/goaws/app/router.actionHandler({0x7ef3b8, 0xc0004f8620}, 0xc000229700)
sqs       |     /home/runner/work/goaws/goaws/app/router/router.go:79 +0x1f4
sqs       | net/http.HandlerFunc.ServeHTTP(0xc000229600?, {0x7ef3b8?, 0xc0004f8620?}, 0x0?)
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2084 +0x2f
sqs       | github.com/gorilla/mux.(*Router).ServeHTTP(0xc000254300, {0x7ef3b8, 0xc0004f8620}, 0xc000229500)
sqs       |     /home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
sqs       | net/http.serverHandler.ServeHTTP({0x7ee6f0?}, {0x7ef3b8, 0xc0004f8620}, 0xc000229500)
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2916 +0x43b
sqs       | net/http.(*conn).serve(0xc00013bd60, {0x7ef670, 0xc00029c450})
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1966 +0x5d7
sqs       | created by net/http.(*Server).Serve
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:3071 +0x4db
sqs       | 2024/04/12 22:04:29 http: panic serving 192.168.65.1:64975: invalid WriteHeader code 0
sqs       | goroutine 338 [running]:
sqs       | net/http.(*conn).serve.func1()
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1825 +0xbf
sqs       | panic({0x6fc9c0, 0xc00024f170})
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:844 +0x258
sqs       | net/http.checkWriteHeaderCode(...)
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1111
sqs       | net/http.(*response).WriteHeader(0xc00028a8c0, 0x0)
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1145 +0x879
sqs       | github.com/Admiral-Piett/goaws/app/gosns.createErrorResponse({0x7ef3b8, 0xc00028a8c0}, 0x4a?, {0xc00072e580?, 0x0?})
sqs       |     /home/runner/work/goaws/goaws/app/gosns/gosns.go:777 +0x134
sqs       | github.com/Admiral-Piett/goaws/app/gosns.publishSQS({0x7ef3b8, 0xc00028a8c0}, 0xc000274620?, 0xc0001500a0, {0xc0001445f0, 0x4a}, 0xc000121650, {0x0, 0x0}, {0xc0001445a0, ...}, ...)
sqs       |     /home/runner/work/goaws/goaws/app/gosns/gosns.go:548 +0x551
sqs       | github.com/Admiral-Piett/goaws/app/gosns.Publish({0x7ef3b8, 0xc00028a8c0}, 0xc0002d2127?)
sqs       |     /home/runner/work/goaws/goaws/app/gosns/gosns.go:510 +0x4ea
sqs       | net/http.HandlerFunc.ServeHTTP(...)
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2084
sqs       | github.com/Admiral-Piett/goaws/app/router.actionHandler({0x7ef3b8, 0xc00028a8c0}, 0xc000289900)
sqs       |     /home/runner/work/goaws/goaws/app/router/router.go:79 +0x1f4
sqs       | net/http.HandlerFunc.ServeHTTP(0xc000289800?, {0x7ef3b8?, 0xc00028a8c0?}, 0x0?)
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2084 +0x2f
sqs       | github.com/gorilla/mux.(*Router).ServeHTTP(0xc000254300, {0x7ef3b8, 0xc00028a8c0}, 0xc000289700)
sqs       |     /home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
sqs       | net/http.serverHandler.ServeHTTP({0x7ee6f0?}, {0x7ef3b8, 0xc00028a8c0}, 0xc000289700)
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2916 +0x43b
sqs       | net/http.(*conn).serve(0xc0000a86e0, {0x7ef670, 0xc00029c450})
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1966 +0x5d7
sqs       | created by net/http.(*Server).Serve
sqs       |     /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:3071 +0x4db

**Comment by Admiral-Piett** [comment]
What version of boto are you running?  This is probably an AWS JSON issue, which we know about and are working on.

**Comment by Admiral-Piett** [comment]
@advancedlogic  If you're still having issues, v0.5.0 supports AWS JSON 1.1 Protocol - try that.  If that fails feel free to comment back here.
